stages:
    - build
    - test
    - infrastructure
    - docker_build
    - deploy

compile_python:
    stage: build
    image: python:3.9-slim
    script:
        - cd ./service-python-main
        - pip install -r requirements.txt

test_python:
    stage: test
    image: python:3.9-slim
    script:
        - cd ./service-python-main
        - pip install -r requirements.txt
        - python test_app.py

compile_Java:
  stage: build
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - cd ./service-java-main 
    - mvn compile

test_Java:
  stage: test
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - cd ./service-java-main
    - mvn test 

infrastructure_terraform:
  stage: infrastructure
  image: 
    name: hashicorp/terraform:1.3.9
    entrypoint: [""]
  script:
    - cd ./terraform
    - terraform init
    - terraform apply --auto-approve

docker_build:
  stage: docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - echo $DOCKER_PASSWORD | docker login myacrregistry63737.azurecr.io -u myacrregistry63737 --password-stdin
  script:
    - cd service-python-main
    - docker build -t myacrregistry63737.azurecr.io/python-service:latest .
    - docker push myacrregistry63737.azurecr.io/python-service:latest
    - cd ../service-java-main
    - docker build -t myacrregistry63737.azurecr.io/java-service:latest .
    - docker push myacrregistry63737.azurecr.io/java-service:latest
  variables:
    DOCKER_TLS_CERTDIR: "/certs"






