stages:
    - build
    - test
    - infrastructure
    - deploy

compile_python:
    stage: build
    image: python:3.9-slim
    script:
        - cd ./service-python-main
        - pip install -r requirements.txt
    artifacts:
      paths:
      - ./service-python-main 
      expire_in: 1h  # L'artifact est supprimé après 1 heure

test_python:
    stage: test
    image: python:3.9-slim
    script:
        - cd ./service-python-main
        - pip install -r requirements.txt
        - python test_app.py

compile_Java:
  stage: build
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - cd ./service-java-main
    - mvn compile
  artifacts:
    paths:
      - ./service-java-main/target/  # Conserver le dossier target
    expire_in: 1h  # L'artifact est supprimé après 1 heure

test_Java:
  stage: test
  image: maven:3.9.4-eclipse-temurin-17
  script:
    - cd ./service-java-main
    - mvn test

infrastructure_terraform:
  stage: infrastructure
  image:
    name: hashicorp/terraform:1.3.9
    entrypoint: [""]
  script:
    - cd ./terraform
    - terraform init
    - terraform apply --auto-approve
    
docker_build:
  stage: deploy
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  before_script:
    - apk add --no-cache py3-pip gcc musl-dev python3-dev libffi-dev openssl-dev cargo make
    - pip install azure-cli
    - az login --service-principal -u "$ARM_CLIENT_ID" -p "$ARM_CLIENT_SECRET" --tenant "$ARM_TENANT_ID"
    - az acr login --name myacrregistry63737
  script:
    - cd service-python-main
    - docker build -t myacrregistry63737.azurecr.io/python-service:latest .
    - docker push myacrregistry63737.azurecr.io/python-service:latest
    - cd ../service-java-main
    - docker build -t myacrregistry63737.azurecr.io/java-service:latest .
    - docker push myacrregistry63737.azurecr.io/java-service:latest
  variables:
    DOCKER_TLS_CERTDIR: "/certs"